---
- name: add debian backport repository
  apt_repository:
    repo: 'deb http://http.debian.net/debian jessie-backports main'
    state: present

- name: install ca-certificates package
  apt:
    name: ca-certificates
    update_cache: yes
    state: present

- name: install apt-transport-https package
  apt:
    name: apt-transport-https
    update_cache: yes
    state: present

- name: Install vim
  package: name=vim state=present

- name: Install git
  package: name=git state=present

- name: Install collectl
  apt: name=collectl update_cache=yes state=latest cache_valid_time=3600
  register: installcollectl

- name: Increase filedescriptor limits
  lineinfile: dest=/etc/security/limits.conf line={{ item }} state=present
  with_items:
    - "* soft nofile 1048576"
    - "* hard nofile 1048576"
    - "root soft nofile 1048576"
    - "root hard nofile 1048576"
    - "* soft memlock unlimited"
    - "* hard memlock unlimited"

- name: Increase inotify and memory limits
  sysctl: name={{ item[0] }} value={{ item[1] }} state=present sysctl_file=/etc/sysctl.d/70-limits.conf reload=yes
  with_together:
    - [ 'fs.inotify.max_queued_events', 'fs.inotify.max_user_instances', 'fs.inotify.max_user_watches', 'vm.max_map_count', 'net.ipv4.tcp_max_syn_backlog', 'net.ipv4.tcp_syncookies', 'net.core.wmem_max', 'net.core.rmem_max', 'net.ipv4.tcp_rmem', 'net.ipv4.tcp_wmem', 'net.ipv4.tcp_window_scaling', 'net.core.netdev_max_backlog']
    - [ 1048576, 1048576, 1048576, 262144, 8096, 0, 12582912, 12582912, '10240 87380 12582912', '10240 87380 12582912', 1, 5000]
