---
- name: add debian backport repository
  apt_repository:
    repo: 'deb http://http.debian.net/debian wheezy-backports main'
    state: present

- name: install ca-certificates package
  apt:
    name: ca-certificates
    update_cache: yes
    state: present

- name: install apt-transport-https package
  apt:
    name: apt-transport-https
    update_cache: yes
    state: present

- name: Install vim
  package: name=vim state=present

- name: Install git
  package: name=git state=present

- name: Install collectl
  apt: name=collectl update_cache=yes state=latest cache_valid_time=3600
  register: installcollectl

