---
- name: run experiment
  shell: "rake benchmark:{{ benchmark_task }}"
  args:
    chdir: /srv/benchmark
    executable: /bin/bash
  environment: 
    ADAPTOR_HOST: "{{ resource_adaptor }}:{{ resource_adaptor_port }}"
    EXPERIMENT_ACTORS: "{{ experiment_actors }}" 
    EXPERIMENT_REQUESTS: "{{ experiment_requests }}" 
    EXPERIMENT_TIME: "{{ experiment_time }}" 
    EXPERIMENT_NUMBER: "{{ experiment_number }}"
  register: run

- debug: var=run.stdout_lines

- name: synchronize files
  synchronize: src=/srv/benchmark/results/output.csv dest=/tmp/ mode=pull
