---
- name: run experiment
  shell: 'bash -lc "rake benchmark:{{ benchmark_task }}"'
  args:
    chdir: /srv/benchmark/
  environment: 
    ADAPTOR_HOST: "{{ resource_adaptor }}:{{ resource_adaptor_port }}"
    EXPERIMENT_TIME: "{{ experiment_time }}" 
    EXPERIMENT_CYCLES: "{{ experiment_cycles }}" 
    EXPERIMENT_WAIT: "{{ experiment_cycles_wait }}" 
  register: run

- debug: var=run.stdout_lines

- name: synchronize files
  synchronize: src=/srv/benchmark/results/*.txt dest=/tmp/ mode=pull
