---
- name: run experiment
  shell: 'bash -lc "rake benchmark:{{ benchmark_task }}"'
  args:
    chdir: /srv/benchmark
  environment: 
    ADAPTOR_HOST: "{{ resource_adaptor }}:{{ resource_adaptor_port }}"
    EXPERIMENT_ACTORS: "{{ experiment_actors }}" 
    EXPERIMENT_REQUESTS: "{{ experiment_requests }}" 
    EXPERIMENT_TIME: "{{ experiment_time }}" 
    EXPERIMENT_INTERVAL: "{{ experiment_interval }}" 
    EXPERIMENT_NUMBER: "{{ experiment_number }}"
    MAX_NUMBER: "{{ max_number }}"
  register: run

- debug: var=run.stdout_lines

- name: synchronize files
  synchronize: src=/srv/benchmark/results/output* dest=/tmp/ mode=pull
