---

- name: create redis
  docker_container:
    name: data-collector-redis
    image: redis
    state: started
    restart: yes

- name: create data-collector API service
  docker_container:
    name: data-collector
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    links:
    - 'postgres'
    - 'data-collector-redis'
    volumes:
    - /data-collector/
    ports:
    - "3000:3000"
    env:
      RAILS_ENV: "{{ rails_env }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_PORT: "{{postgres_port}}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"

- name: create database
  command: docker exec data-collector rake db:create

- name: migrate database
  command: docker exec data-collector rake db:migrate

- name: create data-collector collector service
  docker_container:
    name: data-collector-collector
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    links:
    - 'postgres'
    - 'data-collector-redis'
    command: rails runner scripts/collect.rb
    volumes:
    - /data-collector/
    env:
      RAILS_ENV: "{{ rails_env }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_PORT: "{{postgres_port}}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"

- name: create data-collector resource create service
  docker_container:
    name: data-collector-create
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    links:
    - 'postgres'
    - 'data-collector-redis'
    command: rails runner scripts/create_resources.rb
    volumes:
    - /data-collector/
    env:
      RAILS_ENV: "{{ rails_env }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_PORT: "{{postgres_port}}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"

- name: create data-collector resource update service
  docker_container:
    name: data-collector-update
    image: "{{ docker_image }}"
    state: started
    recreate: yes
    links:
    - 'postgres'
    - 'data-collector-redis'
    command: rails runner scripts/update_resources.rb
    volumes:
    - /data-collector/
    env:
      RAILS_ENV: "{{ rails_env }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_PORT: "{{postgres_port}}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"
