---

- name: create redis
  docker_container:
    name: data-collector-redis
    image: redis
    state: started

- name: create data-collector service
  docker_container:
    name: data-collector
    image: "{{ docker_image }}"
    state: started
    links:
    - 'postgres'
    - 'data-collector-redis'
    volumes:
    - /data-collector/
    ports:
    - "3000:3000"
    env:
      RAILS_ENV: "{{ rails_env }}"
      POSTGRES_HOST: "{{ postgres_host }}"
      POSTGRES_PORT: "{{postgres_port}}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      RABBITMQ_HOST: "{{ rabbitmq }}"

- name: create database
  command: docker exec data-collector rake db:create

- name: migrate database
  command: docker exec data-collector rake db:migrate
