---

- name: Install apache2
  apt: name=apache2 update_cache=yes state=latest cache_valid_time=3600

- name: Enabling and start apache2
  service: name=apache2 enabled=yes state=started
  register: apache2started

- name: Basic configuration of apache2
  lineinfile: dest=/etc/apache2/apache2.conf line="ServerName localhost"

- name: Setup Virtual Hosts
  register: createvhost
  template:
    src: templates/httpd-vhosts.conf.j2
    dest: /etc/apache2/sites-available/benchmark-lss.com.conf
    with_items: "{{ debian_log_dir }}"

- name: Enabling Virtual Host
  when: createvhost|success
  shell: a2ensite benchmark-lss.com.conf
  register: enabledvirtualhost

- name: Disabling Default Virtual Host
  when: enabledvirtualhost|success
  shell: a2dissite 000-default.conf
  register: disabledvirtualhost

- name: Turn off current mpm module
  when: disabledvirtualhost|success
  shell: a2dismod mpm_*
  register: disabledevent

- name: Enable event module
  when: disabledevent|success
  shell: a2enmod mpm_event
  register: enabledevent

- name: Restart apache2 to capture the new configuration
  when: enabledevent|success
  service: name=apache2 state=restarted
