apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  name: data-collector
  labels:
    app: data-collector
spec:
  ports:
  - port: 3000
    name: http
  clusterIP: None
  selector:
    app: data-collector

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-collector
  labels:
    name: data-collector
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: data-collector
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: data-collector
          image: arthurmde/data-collector:0.2-0.1-exp2
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: MONGO_USER
              value: 'admin'
            - name: MONGO_PASSWORD
              value: 'admin'
            - name: MONGO_HOST
              value: 'mongo'
            - name: MONGO_PORT
              value: '27017'
            - name: RABBITMQ_HOST
              value: 'rabbitmq'
            - name: KONG_URI
              value: 'http://kong-admin:8001'
            - name: REGISTER_METHOD
              value: 'target'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: [ "/bin/sh", "-c", "export SELF_HOST=$MY_POD_IP:3000 && bundle exec rails s -p 3000 -b 0.0.0.0" ]
          resources:
            requests:
              memory: "200M"
              cpu: "0.2"
            limits:
              memory: "2G"
