apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  name: resource-adaptor
  labels:
    app: resource-adaptor
spec:
  ports:
  - port: 3000
    name: http
  clusterIP: None
  selector:
    app: resource-adaptor

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resource-adaptor
  labels:
    name: resource-adaptor
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: resource-adaptor
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: resource-adaptor
          image: arthurmde/resource-adaptor:0.2-0.3-exp2
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: POSTGRES_USER
              value: stolon
            - name: POSTGRES_PASSWORD
              value: interscity
            - name: POSTGRES_HOST
              value: stolon-proxy-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: RABBITMQ_HOST
              value: 'rabbitmq'
            - name: KONG_URI
              value: 'http://kong-admin:8001'
            - name: CATALOGUER_HOST
              value: 'kong-proxy:8000/catalog'
            - name: ADAPTOR_HOST
              value: 'kong-proxy:8000/adaptor'
            - name: REGISTER_METHOD
              value: 'target'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: [ "/bin/sh", "-c", "rm tmp/pids/server.pid && export SELF_HOST=$MY_POD_IP:3000 && bundle exec rails s -p 3000 -b 0.0.0.0" ]
          resources:
            requests:
              memory: "200M"
              cpu: "0.2"
