apiVersion: batch/v1
kind: Job
metadata:
  name: resource-cataloguer-migration
spec:
  template:
    metadata:
      name: resource-cataloguer-migration
    spec:
      containers:
      - name: resource-cataloguer-migration
        image: arthurmde/resource-cataloguer:0.2-0.3-exp2
        env:
          - name: POSTGRES_USER
            value: stolon
          - name: POSTGRES_PASSWORD
            value: interscity
          - name: POSTGRES_HOST
            value: stolon-proxy-service
          - name: POSTGRES_PORT
            value: '5432'
          - name: RABBITMQ_HOST
            value: 'rabbitmq'
          - name: KONG_URI
            value: 'http://kong-admin:8001'
          - name: REGISTER_METHOD
            value: 'target'
          - name: PGPASSWORD
            value: 'interscity'
        command:
        - /bin/sh
        - -c
        - >
          rake db:create;
          apt-get update;
          apt-get install wget -y;
          wget https://www.ime.usp.br/~esposte/documents/interscity-experiments/resource_cataloguer_development-2017-10-25.tar.gz -O /tmp/resource_cataloguer_development.tar.gz;
          gunzip /tmp/resource_cataloguer_development.tar.gz -d /tmp/resource_cataloguer_development.tar;
          pg_restore -C -d resource_cataloguer_development -h stolon-proxy-service -p 5432 -U stolon /tmp/resource_cataloguer_development.tar;
          rake db:migrate;
      restartPolicy: Never
