---
- name: install nginx package
  apt:
    name: nginx
    state: present

- name: remove default configuration in sites enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent   

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy proxy configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

