---
- name: install basic setup
  hosts: 
    - all
  user: root
  become: yes
  roles:
    - common

- name: docker setup
  hosts:
    - platform
    - rabbitmq
  user: root
  become: yes
  roles:
    - docker

- name: install postgres
  hosts: platform
  user: root
  become: yes
  roles:
    - postgres

- name: setup rabbitmq
  hosts: rabbitmq
  user: root
  become: yes
  roles:
    - rabbitmq

- name: setup resource-adaptor
  hosts: resource-adaptor
  user: root
  become: yes
  roles:
    - resource-adaptor

- name: setup resource-cataloguer
  hosts: resource-cataloguer
  user: root
  become: yes
  roles:
    - resource-cataloguer

- name: setup data-collector
  hosts: data-collector
  user: root
  become: yes
  roles:
    - data-collector

- name: setup nginx
  hosts: nginx
  user: root
  become: yes
  roles:
    - nginx
